### ISSUE TITLE
problem with jsonlib:jar dependency

### ISSUE THREAD

**Issue by rkiddy** [hufuman/excel2db#1]
Any hints? Thanks.

     $ mvn -v
     Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
     Maven home: /usr/local/apache-maven-3.3.3
     Java version: 1.8.0_66, vendor: Oracle Corporation
     Java home: /usr/lib/jvm/java-8-oracle/jre
     Default locale: en_US, platform encoding: UTF-8
     OS name: "linux", version: "3.16.0-51-generic", arch: "amd64", family: "unix"

     $ mvn compile
     [INFO] Scanning for projects...
     [INFO]                                                                         
     [INFO] ------------------------------------------------------------------------
     [INFO] Building excel2db 1.0
     [INFO] ------------------------------------------------------------------------
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.pom (8 KB at 13.1 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/23/maven-plugins-23.pom (9 KB at 57.2 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/22/maven-parent-22.pom (30 KB at 148.2 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/11/apache-11.pom (15 KB at 198.1 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-resources-plugin/2.6/maven-resources-plugin-2.6.jar (29 KB at 107.2 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.pom (10 KB at 101.7 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-plugins/24/maven-plugins-24.pom (11 KB at 118.6 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/maven-parent/23/maven-parent-23.pom (32 KB at 294.7 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/apache/13/apache-13.pom (14 KB at 155.1 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar
     Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.1/maven-compiler-plugin-3.1.jar (42 KB at 98.7 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/jexcelapi/jxl/2.6.12/jxl-2.6.12.pom
     Downloaded: https://repo.maven.apache.org/maven2/net/sourceforge/jexcelapi/jxl/2.6.12/jxl-2.6.12.pom (2 KB at 21.7 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.14/log4j-1.2.14.pom
     Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.14/log4j-1.2.14.pom (3 KB at 32.7 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.27/mysql-connector-java-5.1.27.pom
     Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.27/mysql-connector-java-5.1.27.pom (2 KB at 15.4 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.pom (3 KB at 39.2 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-parent/1.7.5/slf4j-parent-1.7.5.pom (12 KB at 160.1 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/json/jsonlib/1.0/jsonlib-1.0.pom
     [WARNING] The POM for org.json:jsonlib:jar:1.0 is missing, no dependency information available
     Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.pom
     Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.pom (3 KB at 20.1 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom (766 B at 13.6 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom
     Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom (2 KB at 33.8 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/jexcelapi/jxl/2.6.12/jxl-2.6.12.jar
     Downloading: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.14/log4j-1.2.14.jar
     Downloading: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.27/mysql-connector-java-5.1.27.jar
     Downloading: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar
     Downloading: https://repo.maven.apache.org/maven2/org/json/jsonlib/1.0/jsonlib-1.0.jar
     Downloading: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.jar
     Downloaded: https://repo.maven.apache.org/maven2/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar (26 KB at 91.0 KB/sec)
     Downloading: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
     Downloaded: https://repo.maven.apache.org/maven2/log4j/log4j/1.2.14/log4j-1.2.14.jar (359 KB at 425.2 KB/sec)
     Downloaded: https://repo.maven.apache.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar (44 KB at 46.1 KB/sec)
     Downloaded: https://repo.maven.apache.org/maven2/net/sourceforge/jexcelapi/jxl/2.6.12/jxl-2.6.12.jar (709 KB at 605.7 KB/sec)
     Downloaded: https://repo.maven.apache.org/maven2/junit/junit/4.11/junit-4.11.jar (240 KB at 201.6 KB/sec)
     Downloaded: https://repo.maven.apache.org/maven2/mysql/mysql-connector-java/5.1.27/mysql-connector-java-5.1.27.jar (852 KB at 641.5 KB/sec)
     [INFO] ------------------------------------------------------------------------
     [INFO] BUILD FAILURE
     [INFO] ------------------------------------------------------------------------
     [INFO] Total time: 4.955 s
     [INFO] Finished at: 2015-10-24T11:23:31-07:00
     [INFO] Final Memory: 8M/240M
     [INFO] ------------------------------------------------------------------------
     [ERROR] Failed to execute goal on project excel2db: Could not resolve dependencies for project excel2db:excel2db:jar:1.0: Could not find artifact org.json:jsonlib:jar:1.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
     [ERROR] 
     [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
     [ERROR] Re-run Maven using the -X switch to enable full debug logging.
     [ERROR] 
     [ERROR] For more information about the errors and possible solutions, please read the following articles:
     [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by hufuman** [comment]
<dependency>
	<groupId>net.sf.json-lib</groupId>
	<artifactId>json-lib</artifactId>
	<version>2.4</version>
</dependency>

try to use this config.

And this project isn't under maintainance anymore.
